# Generated by Django 3.2.9 on 2022-08-24 09:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_lastname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.TextField()),
                ('organization', models.TextField()),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('coach', 'Debate coach'), ('parent', 'Parent'), ('student', 'Student')], default='student', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField(default='Description missing. Please notify the administrator.')),
                ('equipment', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='')),
                ('material_type', multiselectfield.db.fields.MultiSelectField(choices=[('lesson', 'Lesson plan'), ('coaching', 'Coaching guide'), ('program', 'Program guide'), ('curriculum', 'Curriculum')], max_length=10)),
                ('language', multiselectfield.db.fields.MultiSelectField(choices=[('EN', 'English'), ('HR', 'Croatian'), ('NL', 'Dutch'), ('SL', 'Slovenian'), ('SK', 'Slovak'), ('PL', 'Polish')], max_length=17)),
                ('topic', multiselectfield.db.fields.MultiSelectField(choices=[('argumentation', 'Argumentation and reasoning'), ('case', 'Case building'), ('evidence', 'Empirical evidence and knowledge'), ('games', 'Exercises and debate club games'), ('intro', 'Introduction to debate and debate formats'), ('analysis', 'Non-argumentative analysis'), ('public speaking', 'Public speaking'), ('critical thinking', 'Critical thinking'), ('motion analysis', 'Motion analysis'), ('teacher development', 'Coach/teacher development'), ('program development', 'Debate program development')], max_length=138)),
                ('difficulty', multiselectfield.db.fields.MultiSelectField(choices=[('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], max_length=30)),
                ('age', multiselectfield.db.fields.MultiSelectField(choices=[('under 14', 'Under 14'), ('between 14 and 19', 'Between 14 and 19'), ('over 19', 'Over 19')], max_length=34)),
                ('duration', multiselectfield.db.fields.MultiSelectField(choices=[('45 min', '45 minutes'), ('60-90 min', '60 - 90 minutes'), ('over 90 min', 'over 90 minutes')], max_length=28)),
                ('activity_type', multiselectfield.db.fields.MultiSelectField(choices=[('2yr', '2-year debate program'), ('1yr', '1-year debate program'), ('6mo', '6-month debate program'), ('short', 'Short term debate program')], max_length=17)),
                ('links', models.ManyToManyField(blank=True, to='lessons.Link')),
                ('similar_to', models.ManyToManyField(blank=True, to='lessons.Lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
