# Generated by Django 3.2.9 on 2022-08-28 10:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20220828_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='age_and_difficulty',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('under 14', 'Under 14'), ('between 14 and 19', 'Between 14 and 19'), ('over 19', 'Over 19'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], default=('advanced', 'Advanced'), max_length=65),
        ),
    ]
