# Generated by Django 3.2.9 on 2022-08-28 14:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_age_and_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='age_and_difficulty',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('under_14', 'Under 14'), ('between_14_and_19', 'Between 14 and 19'), ('over_19', 'Over 19'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], default=('advanced', 'Advanced'), max_length=65),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('45_min', '45 minutes'), ('between_60_and_90 min', '60 - 90 minutes'), ('over_90_min', 'over 90 minutes')], max_length=40),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('argumentation', 'Argumentation and reasoning'), ('case', 'Case building'), ('evidence', 'Empirical evidence and knowledge'), ('games', 'Exercises and debate club games'), ('intro', 'Introduction to debate and debate formats'), ('analysis', 'Non-argumentative analysis'), ('public_speaking', 'Public speaking'), ('critical_thinking', 'Critical thinking'), ('motion_analysis', 'Motion analysis'), ('teacher_development', 'Coach/teacher development'), ('program_development', 'Debate program development')], max_length=138),
        ),
    ]
