# Generated by Django 3.2.9 on 2022-08-30 13:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20220828_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='material_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lesson', 'Lesson plan'), ('coaching', 'Coaching guide'), ('program', 'Program guide'), ('curriculum', 'Curriculum')], max_length=34),
        ),
    ]
