apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lesson-plans
resources:
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/ingress.yaml
images:
  - name: lesson-plans-backend
    newName: rg.fr-par.scw.cloud/djnd/lesson-plans-backend
    newTag: 'latest'
  - name: lesson-plans-frontend
    newName: rg.fr-par.scw.cloud/djnd/lesson-plans-frontend
    newTag: 'latest'
