
version: '3'

volumes:
  postgres-data:

services:
  backend:
    build: ./backend
    working_dir: /code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:changeme@db/lesson_plans
      PYTHONPATH: /code:$PYTHONPATH
      AWS_ACCESS_KEY_ID: SCW30TQKN6GH1444F68W
      AWS_SECRET_ACCESS_KEY: a81e9263-250a-4dda-8995-50a3371a456a
      ENABLE_S3: True
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lesson_plans
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
